phrase:
  access_token: 968908696c62a8800722d9c7df3c0c01106bc28f7c47e5c4d9d75e600687c982
  project_id: 
  file_format: "json"
  push:
    sources:
    - file: ./src/phrase/soporte-kw-es.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./src/phrase/soporte-kw-es.json
      params:
        file_format: simple_json
